vim.o.colorcolumn = "120" -- Highlight column 120
vim.o.termguicolors = true -- Enable true colors
vim.o.ignorecase = true -- Ignore case in search patterns
vim.o.smartcase = true -- Override the 'ignorecase' option if the search pattern contains upper case characters
vim.o.swapfile = false -- Disable swap files
vim.o.autoindent = true -- Enable auto indentation
vim.o.smartindent = true -- Do smart autoindenting when starting a new line
vim.o.expandtab = true -- Use spaces instead of tabs
vim.o.tabstop = 2 -- Number of spaces for a tab
vim.o.softtabstop = 2 -- Number of spaces for a tab when editing
vim.o.shiftwidth = 2 -- Number of spaces for autoindent
vim.o.shiftround = true -- Round indent to multiple of shiftwidth
vim.o.list = true -- Show whitespace characters
vim.o.listchars = "multispace:·,lead:·,trail:·,tab:> ,nbsp:+" -- Characters to show for tabs, spaces, and end of line
vim.o.number = true -- Show line numbers
vim.o.relativenumber = true -- Show relative line numbers
vim.o.numberwidth = 2 -- Width of the line number column
vim.o.wrap = false -- Disable line wrapping
vim.o.cursorline = true -- Highlight the current line
vim.o.scrolloff = 8 -- Keep 8 lines above and below the cursor
vim.o.inccommand = "nosplit" -- Shows the effects of a command incrementally in the buffer
vim.o.completeopt = "menuone,popup,noinsert,fuzzy" -- Options for completion menu
vim.o.splitright = true -- Open vertical split right
vim.o.splitbelow = true -- Open horizontal split below
vim.g.mapleader = " " -- Special character for advanced commands
vim.g.loaded_netrw = 1 -- Disable builtin file explorer
vim.g.loaded_netrwPlugin = 1
-- vim.cmd.filetype("plugin indent on") -- Enable filetype detection, plugins, and indentation
